CHANGELOG.md
frontend/webapp/core/__init__.py

Resolving issue with roles on registration process (https://github.com/FORTH-ICS-INSPIRE/artemis/issues/52)
#52

Fix bug with roles in registration (Closes #52)

---

frontend/Dockerfile
frontend/minify-js.sh

Builder on the frontend container used a very old version of google's closure compiler so we build it on the fly now.
#77

Build latest container for GCC (Closes #77)

---

.env
docker-compose.yaml
other/postgres-backup.sh
other/postgres-cleanup.sh
other/postgres-entrypoint.sh

Changed entrypoint of database's container to start the cron daemon by itself and also we map a new file that cleans all non-hijack BGP updates.
Resolves #33

Auto-clean no-hijack BGP updates (Closes #33)

---

backend/core/database.py

Resolves #110 
Switched from dict to string hashing

Switched dumping from config dict to raw_config str (Closes #110)

---

CHANGELOG.md
backend/entrypoint
backend/entrypoint.test

Allowing backend runs on newer DBs than intended
entrypoint, entrypoint.test
Resolves #

Fixing backend behavior when running old containers on newer DBs than intended

---

CHANGELOG.md
backend/core/database.py
backend/core/detection.py
backend/core/utils/__init__.py

database and detection
Resolves #119 
Added the origin, neighbor combinations as strings in redis sets related to ongoing hijacks

Store (origin, neighbor) combinations of hijack BGP updates in redis (Closes #119)

---

CHANGELOG.md
backend/core/database.py

Slight changes in redis BGP update bootstrap logic on DB init.
database.py
Resolves #155 
Revision of bootstrapping logic

Fixed redis BGP update bootstrap logic (Closes #155)

---

.env
CHANGELOG.md
backend/core/database.py
backend/core/detection.py
backend/hasura_init.json
backend/migrate/migrations/scripts/migration_16.sql
backend/migrate/migrations/target_steps.json
backend/testing/db/data/tables.sql
frontend/webapp/render/static/js/custom/display_info.js
frontend/webapp/render/templates/main/overview.htm
other/db/data/tables.sql

Resolves #152 
Pre-load the set of monitor peers from the stored DB BGP updates. Load this into redis, and update
redis whenever a new BGP update is seen. Update DB only if the redis set actually changes.

DB stat on number of monitor peers

---

CHANGELOG.md
backend/core/detection.py
backend/core/utils/__init__.py

Sends the hijack event as a JSON parsable string to the hijack logger. 
Resolves #

JSON dump the monitor event for easier parsing

---

CHANGELOG.md
backend/core/configuration.py

Resolves #186 
Take care of 'None' strings in redis values.

fixed bug in configuration (translation of hijacks to rules)

---

artemis-chart/templates/backend-deployment.yaml
artemis-chart/templates/monitor-deployment.yaml

Previously when the backend pod restarted it would overwrite the config file in persistent storage with the one from the configmap (i.e., the default). The `-u` option to `cp` doesn't seem to be enough to prevent an overwrite (presumably the modification time of the file from the configmap cannot be trusted). Using both `-u` and the `-n` (no-clobber) option seems to work and prevent the persisted config file from being overwritten.
Resolves #

Ensure ARTEMIS config file is not clobbered on pod restart

---

CHANGELOG.md
tester/autoconf/supervisor.d/services.conf
tester/autoconf/tester.py
tester/detection/supervisor.d/services.conf
tester/rpki/supervisor.d/services.conf

Resolves #349 
Disabled coverage run on autoconf observer for the test. Same for the rest of the tests where we applied "coverage run". Substituted with simple python.

Disabling coverage run on autoconf, using simple python instead

---

CHANGELOG.md
artemis-chart/templates/nginx-deployment.yaml
docker-compose.testcafe.yaml
docker-compose.yaml
vagrant-vm/vagrant-docker-compose.yaml

Upgrade nginx to latest released version (v1.17)

---

CHANGELOG.md
monitor/Dockerfile

Resolves #372
- [x This change requires a change in the documentation.

Upgrade bgpstream to latest (closes #372)

---

backend/Dockerfile
frontend/Dockerfile
monitor/Dockerfile

Moved all the base images for artemis to a monorepo to have easier control over the releases and versions.

Move base images to a monorepo

---

monitor/core/taps/bgpstreamkafka.py

Small bypass fix for #411
Introduced an environment variable called `BGPSTREAM_TIMESTAMP_BYPASS` which when defined for the monitor container sets the start time of bgpstreamkafka to 0. This is needed because PyBGPStream is not yet exposing the correct timestamp when parsing and we have this fix temporarily.
Resolves #

fix: override BGPSTREAM timestamp when not parsed correctly

---

frontend/webapp/render/views/actions_view.py

This bug was raised by @pputerla in #410. We now delete the roles when also deleting the user to avoid issues with permissions when a user with same username is being re-registered after deletion.
Resolves #

fix: delete roles when deleting user

---

CHANGELOG.md
backend/core/utils/__init__.py
docker-compose.yaml
frontend/webapp/utils/__init__.py
monitor/core/utils/__init__.py

Add support for GRAPHQL_URI in backend and monitor codebases. If this is not set, default to constructing the URI using the original URI string using values from from HASURA_HOST and HASURA_PORT (which default to 'graphql' and '8080' respectively)
Resolves #416
Adds the missing env variables to docker-compose.yaml. The monitor and backend processes now build the GRAPHQL_URI using the following logic:
If GRAPHQL_URI is specified in env, use this value
If it is not, build the URI using the values in HASURA_HOST and HASURA_PORT. For backwards compatibility, these default to 'graphql' and port '8080' respectively.

GRAPHQL_URI env support (close/fix #416)

---

backend/core/database.py
backend/core/detection.py
backend/core/tests/test_detection.py
testing/autoignore/tester.py
testing/detection/configs/config.yaml
testing/detection/tester.py
testing/detection/testfiles/implicit_withdrawal_subprefix.json
testing/rpki/tester.py

Resolves #438 
Blocks #436 #437 
The main logic of this PR is the following:
1. Assume we have an active hijack for prefix N/M (where N = network address and M = prefix length) .
2. Currently, we treat correct routing updates for N/M as implicit withdrawals for the monitor that saw both the hijack and the "healed" path.
3. With this adjustment, we also treat correct routing updates for either N_1/M+1 or N_2/M+1 (where N_1, N_2 the network addresses of the direct more specifics of the original prefix) as implicit withdrawals for the hijacked N/M. 
Note that in a future issue we need to carefully account for what prefix space is currently healed; this PR is an …

Implicit withdrawals are now generated also on correct subprefix routing

---

.env
artemis-chart/templates/configmap.yaml
artemis-chart/values.yaml
backend/hasura_init.json
backend/migrate/migrations/scripts/migration_22.sql
backend/migrate/migrations/target_steps.json
other/db/data/tables.sql
testing/detection/db/data/tables.sql
testing/testcafe/tests/simple-flow.js

#448  I have create the new table named "dataplane_msms" in which we will save the results of the dataplane measurements (ping, traceroutes from RIPE Atlas) for a specific hijack detected by ARTEMIS. Furthermore, I have create a new view named "view_dataplane_msms" which help us to query the measurement results from the "dataplane_msms" in a safe manner for each hijack and display these to the frontend (with the help of the Graphql API)        
Resolves #448

New table (dataplane_msms) and view (view_dataplane_msms) creation for hijack dataplane measurements (pings and traceroutes) #448

---

backend/core/configuration.py
backend/core/detection.py
backend/core/tests/test_configuration.py
backend/core/tests/test_detection.py
docs/basicconf.md
docs/hijackinfo.md
frontend/webapp/render/static/js/custom/display_info.js
frontend/webapp/render/templates/main/hijacks.htm
frontend/webapp/render/templates/main/overview.htm

Resolves #443  #441
Need to update docs with new hijack type (in path dimension) called "P" (Pattern)

Prepend sequence pattern matching plus in-unit-test rules

---

artemis-chart/templates/redis-deployment.yaml
backend-services/configs/redis.conf
docker-compose.benchmark.yaml
docker-compose.testautoconf.yaml
docker-compose.testautoignore.yaml
docker-compose.testdetection.yaml
docker-compose.testrpki.yaml
docker-compose.yaml
docs/changelog.md
docs/installsetup.md
other/docker-compose.testcafe.yaml
vagrant-vm/vagrant-docker-compose.yaml

added correct redis command in compose to read conf file on startup

---

backend-services/autoignore/core/autoignore.py
backend-services/autostarter/core/autostarter.py
backend-services/configuration/core/configuration.py
backend-services/database/core/database.py
backend-services/detection/core/detection.py
backend-services/fileobserver/core/observer.py
backend-services/mitigation/core/mitigation.py
backend-services/notifier/core/notifier.py
backend-services/prefixtree/core/prefixtree.py
docs/changelog.md
frontend/webapp/core/modules.py
monitor-services/bgpstreamhisttap/core/bgpstreamhist.py
monitor-services/bgpstreamkafkatap/core/bgpstreamkafka.py
monitor-services/bgpstreamlivetap/core/bgpstreamlive.py
monitor-services/exabgptap/core/exabgp_client.py
monitor-services/riperistap/core/ripe_ris.py

Reconfiguration flag and status in health + responsive config save

---

docs/changelog.md
docs/hijackinfo.md
frontend/webapp/render/templates/main/hijack.htm

Resolves #257 #446 
Simple functionality addition in hijack details page.

Hijack JSON export functionality

---

docs/changelog.md
frontend/webapp/core/__init__.py

Minor fix in session timeout behavior

---

backend-services/configuration/core/configuration.py

Remove process parallelism from re-configuration task

---

backend-services/prefixtree/core/prefixtree.py

Resolves #610 
The issue hits whenever there is a config change while Artemis is running. It does not occur if one shuts down all containers and starts again.
It looks as if prefixtree remains stale for either v4 or v6 after changes. With this in mind I did a deep dig into prefixtree module. Here is what I found:
- Upon initialization prefix_tree_recalculate is set to True https://github.com/FORTH-ICS-INSPIRE/artemis/blob/master/backend-services/prefixtree/core/prefixtree.py#L437
- Upon config changes prefix_tree_recalculate is set again to True and the first prefix that triggers this method: https://github.com/FORTH-ICS-INSPIRE/artemis/blob/master/backend-services/pr …

Split prefixtree recalculation indicator (fixes #610)

---

utils/artemis_utils/service.py
utils/setup.py

update compose dns routine to use dnspython. gethostbyaddr and gethostbyname only return single responses on alpine/musl. Fix for podman
Update service_to_ips_and_replicas_in_compose to use dnspython instead of gethostbyaddr and gethostbyname. Alpine uses musl which only returns a single answer. Returning a single answer to a DNS PTR record prevents the solution running on podman as podman inserts multuple PTR values (container id, instance name, service name)
PR required dnspython to be a dependency for utils package. 
Resolves #
#672
use dnspython to complete dns lookups instead of socket.gethostbyaddr
bugfix

update compose dns routine to use dnspython.
