.bandit
backend/Dockerfile
backend/core/database.py
backend/core/detection.py
backend/core/listener.py
backend/core/mitigation.py
backend/core/monitor.py
backend/core/observer.py
backend/core/scheduler.py
backend/core/taps/betabmp.py
backend/core/taps/bgpstreamhist.py
backend/core/taps/bgpstreamlive.py
backend/core/taps/exabgp_client.py
backend/core/taps/utils.py
frontend/webapp/configs/config.py
frontend/webapp/core/__init__.py
frontend/webapp/core/actions.py
frontend/webapp/core/fetch_config.py
frontend/webapp/core/modules.py
frontend/webapp/templates/forms/__init__.py
frontend/webapp/views/actions/actions_view.py
frontend/webapp/views/main/main_view.py
migrate/migrate.py
other/parsers_collectors/parse_collectors.py

Code Quality Improvements

---

CHANGELOG.md
frontend/webapp/core/__init__.py

GraphQL API with JWT tokens

---

README.md
backend/.coveragerc
backend/Dockerfile.test
backend/core/scheduler.py
backend/docker-compose.test-backend.yml
backend/entrypoint.test
backend/testing/entrypoint
backend/testing/supervisor.d/services.conf
backend/testing/tester.py

Code Coverage Support

---

.env
CHANGELOG.md
backend/migrate/migrations/scripts/migration_8.sql
backend/migrate/migrations/target_steps.json
backend/testing/db/data/tables.sql
frontend/webapp/static/js/custom/display_info.js
frontend/webapp/static/js/custom/utils.js
frontend/webapp/templates/index.htm
frontend/webapp/views/main/templates/bgpupdates.htm
frontend/webapp/views/main/templates/hijacks.htm
other/db/data/tables.sql

Resolves issues https://github.com/FORTH-ICS-INSPIRE/artemis/issues/71 and https://github.com/FORTH-ICS-INSPIRE/artemis/issues/76.
The hijacks are now sorted based on time_last value.
File display_info.js is now optimized. 
Moved DB to version 8.
https://github.com/FORTH-ICS-INSPIRE/artemis/issues/71
https://github.com/FORTH-ICS-INSPIRE/artemis/issues/76

Added time_last and optimize js (Closes #71, #76)

---

CHANGELOG.md
backend/core/database.py
backend/testing/configs/config.yaml
backend/testing/messages.json
backend/testing/tester.py

Updated costly db query
https://github.com/FORTH-ICS-INSPIRE/artemis/issues/83
Revised query based on LEFT JOINs

Withdrawn peer removal optimization (Closes #83)

---

CHANGELOG.md
backend/core/configuration.py
backend/core/utils/__init__.py
backend/testing/configs/config.yaml
backend/testing/messages.json

Changes in configuration to translated configured prefixes from RFC2622-compliant notation to actual prefixes.
Configuration (and its utils)
https://github.com/FORTH-ICS-INSPIRE/artemis/issues/85
Added support in configuration during prefix flattening (rfc2622 translator for prefixes)
Need to update the wiki at a later step.

Support for rfc2622 operators in prefix configuration (Closes #85)

---

.env
CHANGELOG.md
backend/core/configuration.py
backend/core/taps/ripe_ris.py
backend/core/taps/utils.py
backend/requirements.txt

updated ris live client
taps/ripe_ris.py
https://github.com/FORTH-ICS-INSPIRE/artemis/issues/82
updated ris live client

First version of new ris live service websocket client (Closes #82)

---

.pre-commit-config.yaml
CHANGELOG.md
CONTRIBUTING.md
README.md

We add some pre-commit hooks to avoid having errors on the pushed code.
Resolves #97

Pre-commit hooks support

---

CHANGELOG.md
frontend/webapp/core/__init__.py
frontend/webapp/templates/index.htm
frontend/webapp/views/main/templates/hijacks.htm

View hijack by key
- Enable sorting for columns: # Peers Seen/# ASes Infected
Resolves #

sort columns # Peers Seen/# ASes Infected, view hijack by key (Closes issue #88)

---

backend/entrypoint
backend/entrypoint.test
backend/testing/entrypoint
frontend/entrypoint

There was a possibility that the wait-for would time-out and the application will run with unknown behavior. Instead we wait until all of them become available.
Resolves #129
Resolves #127

Wait-for forever until the service is up

---

CHANGELOG.md
backend/core/taps/betabmp.py
backend/core/taps/bgpstreamhist.py
backend/core/taps/bgpstreamlive.py
backend/core/taps/exabgp_client.py
backend/core/taps/ripe_ris.py
backend/core/taps/utils.py
backend/docker-compose.test-backend.yml
docker-compose.yaml

Collisions upon update timeouts in redis (misbehaving monitoring sources). The 1,5 hours is to deal with small timing differences that may cause an update to slip through the 2-hour redis time buffer.
Do not accept old updates; however, have an env variable to indicate if a historic replay is in the works so that we bypass this check (suggestion: "HISTORIC"; false by default)
Resolves #135

Do not accept BGP updates older than 1,5 hours (Resolves #135)

---

CHANGELOG.md
frontend/webapp/templates/layout.htm
frontend/webapp/views/actions/actions_view.py
frontend/webapp/views/admin/admin_view.py

add url_for on redirections (Closes #149)

---

CHANGELOG.md
backend/core/monitor.py

Fixed monitor.py
Resolves #154

Fixed RIPE RIS and exaBGP illegal starts (Closes #154)

---

backend/configs/logging.yaml
backend/core/utils/__init__.py

There was an issue when using our custom class for SMTP
Resolves #

Fixed SMTP logger

---

CHANGELOG.md
DEPENDENCIES-LICENSES.md
frontend/webapp/static/js/custom/ripestat.js
frontend/webapp/templates/index.htm
frontend/webapp/views/main/templates/bgpupdates.htm
frontend/webapp/views/main/templates/hijack.htm
frontend/webapp/views/main/templates/hijacks.htm

- Abuse contact details for each ASN (Extracted from RIPEStat)
- Functionality to copy ASN details on clickboard
Resolves #163 #164

abuse contact details + copy to clickboard (#163 #164)

---

CHANGELOG.md
artemis-chart/templates/graphql-deployment.yaml
docker-compose.yaml

Update hasura version from 1.0.0-alpha42 to 1.0.0-alpha44.
Resolves #

update hasura to 1.0.0-alpha44

---

backend/core/database.py
backend/testing/tester.py
backend/testing/testfiles/out_of_order_withdraw.json
backend/testing/testfiles/out_of_order_withdraw_same_peer.json

Ensure latest time_last and earliest time_started (Resolves #168)

---

CHANGELOG.md
backend/configs/logging.yaml
backend/requirements.txt

Add slack logger as a potential handler and an example
Resolves #

Added slack logger and a handler example

---

CHANGELOG.md
artemis-chart/templates/graphql-deployment.yaml
docker-compose.yaml

Update hasura to 1.0.0-alpha45
Resolves #

update hasura to 1.0.0-alpha45

---

CHANGELOG.md
frontend/webapp/core/__init__.py
frontend/webapp/core/proxy_api.py
frontend/webapp/render/templates/main/config_comparison.htm

Frontend now uses only fetch requests. Resolves issue #148 
Resolves #

replace $.ajax with fetch (Resolves #148)

---

frontend/entrypoint

We preload the application before spawning workers to log runtime exceptions on initialization
Resolves #181

Preload application before forking workers (Resolves #181)

---

CHANGELOG.md
backend/core/database.py
backend/core/detection.py
backend/core/utils/__init__.py
backend/testing/testfiles/implicit_withdrawal.json
frontend/webapp/render/static/js/custom/display_info.js
frontend/webapp/render/static/js/custom/utils.js
frontend/webapp/render/templates/main/bgpupdates.htm
frontend/webapp/render/templates/main/hijack.htm

Implicit withdrawals for corrected AS-paths

---

CHANGELOG.md
backend/core/configuration.py
backend/core/database.py
backend/core/detection.py
backend/core/monitor.py
backend/core/utils/__init__.py
backend/testing/configs/config.yaml
backend/testing/testfiles/as_range_tests.json

Support for configured ASN ranges

---

CHANGELOG.md
artemis-chart/templates/graphql-deployment.yaml
docker-compose.yaml

Update hasura to v1.0.0-beta.3
Resolves #

update hasura to v1.0.0-beta.3

---

README.md

updates in README, simplification of steps and wiki outsourcing

---

backend/core/detection.py

Resolves #
Timeout in non-pipeline blpop, retry if timeout is exhibited.

Small fix to avoid detectors being stuck on blpop if token erased

---

.env
artemis-chart/templates/configmap.yaml
artemis-chart/values.yaml
backend/core/database.py
backend/core/utils/__init__.py
backend/hasura_init.json
backend/migrate/migrations/scripts/migration_18.sql
backend/migrate/migrations/target_steps.json
backend/testing/db/data/tables.sql
frontend/webapp/core/modules.py
frontend/webapp/utils/__init__.py
other/db/data/tables.sql

Resolves #231
* persistent intended_process_states table in db
* hasura call in frontend to write intended process states
* recover intended process states and start processes after db startup

Reset the modules to last known state upon restart

---

.env
CHANGELOG.md
artemis-chart/templates/backend-deployment.yaml
artemis-chart/templates/configmap.yaml
artemis-chart/templates/monitor-deployment.yaml
artemis-chart/values.yaml
backend/core/database.py
backend/core/detection.py
backend/core/utils/__init__.py
backend/docker-compose.test-backend.yml
docker-compose.yaml
other/verify_script.py

Resolves #230 
Extended database logging for ignored, deleted, resolved and wthdrawn hijacks (incl. multiple actions). Extended detection logging for outdated hijacks. Extended hijack entry in redis with "end_tag" (withdrawn, resolved, ignored or deleted).
TODO: update https://github.com/FORTH-ICS-INSPIRE/artemis/wiki/Environment-variables with the new env variable HIJACK_LOG_FIELDS
Also to link these variables to this page too: https://github.com/FORTH-ICS-INSPIRE/artemis/wiki/ARTEMIS-logging
Both done.

Additional logging for outdated/withdrawn hijacks

---

docker-compose.yaml

Resolves #192
Always restart composed containers (dependencies are already handled correctly)

restart:always on all containers

---

CHANGELOG.md
monitor/Dockerfile

Upgrade BGPStream to v2.0

---

vagrant-vm/README.md
vagrant-vm/Vagrantfile
vagrant-vm/bootstrap.sh
vagrant-vm/show_artemis_url.sh
vagrant-vm/update_and_start_artemis.sh
vagrant-vm/vagrant-docker-compose.yaml

Vagrant VM automation

---

backend/core/detection.py
docker-compose.routinator.yaml
tester/rpki/configs/config.yaml
tester/rpki/testfiles/test_IL.json
tester/rpki/testfiles/test_NF.json

Minor quick-fix in RPKI section in detection + v6 tests

---

CHANGELOG.md
backend/core/detection.py

Resolves #
Check RPKI status every RTR manager refresh interval instead of per hijack update

Small RPKI val opt

---

CHANGELOG.md
backend/core/database.py

Adding also Ws in bgpupdate_keys

---

.env
artemis-chart/templates/configmap.yaml
artemis-chart/values.yaml
backend/core/configuration.py
backend/core/database.py
backend/core/detection.py
backend/core/listener.py
backend/core/mitigation.py
backend/core/observer.py
backend/migrate/migrations/scripts/migration_20.sql
backend/migrate/migrations/target_steps.json
frontend/webapp/core/actions.py
monitor/core/monitor.py
monitor/core/taps/bgpstreamhist.py
monitor/core/taps/exabgp_client.py
other/db/data/tables.sql
other/db/libs/rabbitmq/schema.sql
other/verify_script.py
testcafe/tests/simple-flow.js
tester/autoconf/tester.py
tester/detection/db/data/tables.sql
tester/rpki/db/data/tables.sql

Acknowledge all rabbitmq messages

---

benchmark/entrypoint
benchmark/executor.py
docker-compose.benchmark.yaml

Add benchmark results for database

---

backend/core/detection.py
tester/detection/configs/config.yaml
tester/detection/testfiles/multirule_prefix.json

multi-rule detection analysis issue fix

---

CHANGELOG.md
backend/core/database.py

http://datamangling.com/2014/01/17/limit-1-and-performance-in-a-postgres-query/
Resolves #

Fix LIMIT query planner bug

---

CHANGELOG.md
backend/core/database.py
backend/core/listener.py
backend/core/utils/tool.py
backend/migrate/migrate.py
backend/migrate/migrations/scripts/migration_unused.py
docker-compose.yaml
monitor/core/listener.py
tester/autoconf/tester.py
tester/detection/tester.py
tester/rpki/tester.py

We create a lot of connections on postgres but we have no way to distinguish between them when debugging. For this purpose I labeled the connections based on the component they are running on.
Resolves #

Added application names on postgres connections

---

CHANGELOG.md
artemis-chart/templates/rabbitmq-deployment.yaml
docker-compose.benchmark.yaml
docker-compose.testautoconf.yaml
docker-compose.testcafe.yaml
docker-compose.testdetection.yaml
docker-compose.testrpki.yaml
docker-compose.yaml
vagrant-vm/vagrant-docker-compose.yaml

Upgrade rabbitmq to latest released version (v3.8.3)

---

CHANGELOG.md
artemis-chart/templates/postgrest-deployment.yaml
docker-compose.testcafe.yaml
docker-compose.yaml
vagrant-vm/vagrant-docker-compose.yaml

Upgrade postgrest to latest released version (v7.0.0)

---

CHANGELOG.md
artemis-chart/templates/graphql-deployment.yaml
docker-compose.testcafe.yaml
docker-compose.yaml
vagrant-vm/vagrant-docker-compose.yaml

Upgrade hasura-engine to latest released version (v1.1.0)

---

frontend/webapp/render/static/css/signin.css

Resolves https://github.com/FORTH-ICS-INSPIRE/artemis/issues/345 css issue with login/register user webpage.

update login css to resolve rendering issue

---

backend/core/utils/__init__.py
frontend/webapp/core/__init__.py

Fix response code on 404 and 500

---

CHANGELOG.md
frontend/webapp/render/templates/main/hijacks.htm

Resolves #261 (reported by @pixitha)

Added Select Page button

---

frontend/requirements.txt
frontend/webapp/configs/nginx.conf
frontend/webapp/core/__init__.py
frontend/webapp/render/templates/admin/system.htm
frontend/webapp/render/templates/admin/user_management.htm
frontend/webapp/render/templates/base/base.htm
frontend/webapp/render/templates/main/bgpupdates.htm
frontend/webapp/render/templates/main/config_comparison.htm
frontend/webapp/render/templates/main/hijack.htm
frontend/webapp/render/templates/main/hijacks.htm
frontend/webapp/render/templates/main/overview.htm
frontend/webapp/render/templates/main/viz.htm
frontend/webapp/render/templates/security/login_user.html
frontend/webapp/render/templates/security/new_password.htm
frontend/webapp/render/templates/security/register_user.html

Moved to flask headers from nginx to cover kubernetes deployment

---

CHANGELOG.md
frontend/webapp/render/static/js/custom/actions.js
frontend/webapp/render/templates/admin/system.htm

Redirect to login page when the session is expired and an action is issued.
Resolves #395

feat: redirect to login page when session expires

---

.flake8
.pre-commit-config.yaml
.travis.yml
backend/Makefile
backend/core/database.py
backend/core/detection.py
backend/core/tests/test_detection.py

Added simple unit-tests for the detection module about hijack types.
Resolves #402

feat: initial unit test for detection BGP handle

---

.env
artemis-chart/templates/frontend-deployment.yaml
docker-compose.testcafe.yaml
docker-compose.yaml
frontend/webapp/core/__init__.py
vagrant-vm/vagrant-docker-compose.yaml

In the CSP policy `connect-src 'self'` doesn't work correctly for wss connections on some browsers (Safari in this case). To fix this we use the environment variable that has the public facing IP or DNS name to set the CSP policy correctly.
Resolves #

fix: added connect-src for wss connection

---

docs/faq.md

Additional FAQ docs around possible issues downoading updates relating to Docker MTU config or host config. Also clean up some missing closing tags from markdown content.
Additional FAQ docs
No related issue (came from discussion Slack Channel)
Adds additional notes around Docker host MTU and possible other config issues, as well as some strategies to help identify and solve.

FAQ Docs update for download failures in container

---

.travis.yml

travis.yml to include fork container creation and CI tests

---

.travis.yml
testing/.coveragerc

Added coverage for unit-tests

---

backend/core/observer.py

fix: observer fix for thread issues

---

backend/core/observer.py

Observer fix v2

---

frontend/webapp/render/static/js/custom/display_info.js
frontend/webapp/render/templates/main/overview.htm

Display info for microservices

---

README.md
backend-services/configs/config.yaml
backend-services/configuration/core/tests/test_configuration.py
docs/autoconfiguration.md
docs/basicconf.md
docs/bgpstreambmp.md
docs/changelog.md
docs/index.md
docs/webapp.md
monitor-services/bgpstreamhisttap/Dockerfile
monitor-services/bgpstreamkafkatap/Dockerfile
monitor-services/bgpstreamlivetap/Dockerfile
monitor-services/bgpstreamlivetap/core/bgpstreamlive.py
monitor-services/exabgptap/Dockerfile
monitor-services/riperistap/Dockerfile
testing/detection/configs/config2.yaml

Testing (lighter) monitor containers, new live projects in bgpstreamlive

---

monitor-services/bgpstreamhisttap/core/bgpstreamhist.py
monitor-services/bgpstreamkafkatap/core/bgpstreamkafka.py
monitor-services/bgpstreamlivetap/core/bgpstreamlive.py
monitor-services/riperistap/core/ripe_ris.py

Non-gracefull kill after timeout expiry for taps

---

.env
backend-services/autoignore/requirements.txt
backend-services/autostarter/requirements.txt
backend-services/configuration/requirements.txt
backend-services/database/requirements.txt
backend-services/detection/requirements.txt
backend-services/fileobserver/requirements.txt
backend-services/mitigation/requirements.txt
backend-services/notifier/requirements.txt
backend-services/prefixtree/requirements.txt
docs/changelog.md
docs/envvars.md
monitor-services/bgpstreamhisttap/requirements.txt
monitor-services/bgpstreamkafkatap/core/bgpstreamkafka.py
monitor-services/bgpstreamkafkatap/requirements.txt
monitor-services/bgpstreamlivetap/core/bgpstreamlive.py
monitor-services/bgpstreamlivetap/requirements.txt
monitor-services/exabgptap/core/exabgp_client.py
monitor-services/exabgptap/requirements.txt
monitor-services/riperistap/core/ripe_ris.py
monitor-services/riperistap/requirements.txt
utils/artemis_utils/redis.py
utils/setup.py

Tap redis expiry checkers (no-data-received)

---

backend-services/autoignore/requirements.txt
backend-services/autostarter/requirements.txt
backend-services/configuration/requirements.txt
backend-services/database/requirements.txt
backend-services/detection/requirements.txt
backend-services/fileobserver/requirements.txt
backend-services/mitigation/requirements.txt
backend-services/notifier/requirements.txt
backend-services/prefixtree/requirements.txt
docs/changelog.md
frontend/requirements.txt
monitor-services/bgpstreamhisttap/requirements.txt
monitor-services/bgpstreamkafkatap/requirements.txt
monitor-services/bgpstreamlivetap/requirements.txt
monitor-services/exabgptap/requirements.txt
monitor-services/riperistap/requirements.txt
testing/detection/requirements.txt
testing/rpki/requirements.txt
utils/setup.py

updated pyyaml and artemis-utils to address depbot fix PRs

---

monitor-services/bgpstreamhisttap/Dockerfile
monitor-services/bgpstreamkafkatap/Dockerfile
monitor-services/bgpstreamlivetap/Dockerfile
monitor-services/exabgptap/Dockerfile
monitor-services/riperistap/Dockerfile

Monitor base container was upgraded to include changes for BGPStream.
Resolves #

Bump monitor base container version for BGPStream

---

docs/changelog.md
monitor-services/bgpstreamhisttap/Dockerfile
monitor-services/bgpstreamkafkatap/Dockerfile
monitor-services/bgpstreamlivetap/Dockerfile
monitor-services/exabgptap/Dockerfile
monitor-services/riperistap/Dockerfile

we recently started getting warnings on our bgpstreamlive tap as follows:
```
bgpstreamlivetap_1   | WARN: INVALID_MSG: unknown bgp4mp subtype 9 (parsebgp_mrt.c:696)
bgpstreamlivetap_1   | 2021-08-24 14:32:48 102: bs_format_mrt.c:264: WARNING: Skipping unknown BGP4MP record subtype 9
bgpstreamlivetap_1   | WARN: INVALID_MSG: unknown bgp4mp subtype 9 (parsebgp_mrt.c:696)
bgpstreamlivetap_1   | 2021-08-24 14:32:48 102: bs_format_mrt.c:264: WARNING: Skipping unknown BGP4MP record subtype 9
bgpstreamlivetap_1   | 2021-08-24 14:32:48 102: bs_format_mrt.c:264: WARNING: Skipping unknown BGP4MP record subtype 9
```
The tap implementation is our classic one here: https://github.com/georgeepta/artemis/blob/master/monitor-services/bgpstreamlivetap/core/bgpstreamlive.py and our base monitor container …

Bumping monitors to 1.0.3 to align to bgpstream 2.2.0

---

README.md

The link to architecture in the table of contents in the read me was incorrect. This PR fixes it.
No
Resolves #614

fix #614 - Corrected link to system architecture 

---

.gitpod.yml
Makefile
README.md
other/frontend/configs/nginx-gitpod.conf

Gitpod support

---

backend-services/autoignore/requirements.txt
backend-services/autostarter/requirements.txt
backend-services/configuration/requirements.txt
backend-services/database/requirements.txt
backend-services/detection/requirements.txt
backend-services/fileobserver/requirements.txt
backend-services/mitigation/requirements.txt
backend-services/notifier/requirements.txt
backend-services/prefixtree/requirements.txt
docs/changelog.md
monitor-services/bgpstreamhisttap/requirements.txt
monitor-services/bgpstreamkafkatap/requirements.txt
monitor-services/bgpstreamlivetap/requirements.txt
monitor-services/exabgptap/requirements.txt
monitor-services/riperistap/requirements.txt
utils/README.md
utils/artemis_utils/envvars.py
utils/artemis_utils/logaux.py
utils/setup.py

fixing broken hijack URL in logs

---

backend-services/autoignore/requirements.txt
backend-services/autostarter/requirements.txt
backend-services/configuration/requirements.txt
backend-services/database/requirements.txt
backend-services/detection/requirements.txt
backend-services/fileobserver/requirements.txt
backend-services/mitigation/requirements.txt
backend-services/notifier/requirements.txt
backend-services/prefixtree/requirements.txt
docs/changelog.md
monitor-services/bgpstreamhisttap/requirements.txt
monitor-services/bgpstreamkafkatap/requirements.txt
monitor-services/bgpstreamlivetap/requirements.txt
monitor-services/exabgptap/requirements.txt
monitor-services/riperistap/requirements.txt
utils/README.md
utils/artemis_utils/service.py
utils/setup.py

It is fixing the service name regex bug.
Resolves #

fix: service

---

.pre-commit-config.yaml
artemis-chart/values.yaml
docker-compose.benchmark.yaml
docker-compose.testautoconf.yaml
docker-compose.testautoignore.yaml
docker-compose.testdetection.yaml
docker-compose.testrpki.yaml
docker-compose.yaml
other/docker-compose.testcafe.yaml
other/verify_script.py
vagrant-vm/vagrant-docker-compose.yaml

Solves https://github.com/FORTH-ICS-INSPIRE/artemis/issues/629 by replacing the removed image.
Resolves #

fix: replace removed image

---

docs/changelog.md
docs/history.md
docs/index.md
docs/webapp.md

fix: doc typo

---

artemis-chart/values.yaml
docker-compose.benchmark.yaml
docker-compose.testautoconf.yaml
docker-compose.testautoignore.yaml
docker-compose.testdetection.yaml
docker-compose.testrpki.yaml
docker-compose.yaml
docs/changelog.md
other/docker-compose.testcafe.yaml
vagrant-vm/vagrant-docker-compose.yaml

fix:  graphql server version bump

---

.github/workflows/ci_cd.yml
artemis-chart/values.yaml
docker-compose.benchmark.yaml
docker-compose.testautoconf.yaml
docker-compose.testautoignore.yaml
docker-compose.testdetection.yaml
docker-compose.testrpki.yaml
docker-compose.yaml
docs/changelog.md
other/docker-compose.testcafe.yaml
vagrant-vm/vagrant-docker-compose.yaml

fix: upgrade image

---

Makefile

feat: add the option to strip build tags from default docker-compose
